[package]
name = "rust-on-your-door"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "string"
path = "src/strings.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
